### ISSUE TITLE
不知道为什么检测不到珍珠QAQ

### ISSUE THREAD

**Issue by bling-yshs** [Sapphire-356/EyeAligningBot#2]
![Snipaste_2022-10-03_11-41-20](https://user-images.githubusercontent.com/41812674/193497688-7293a6e0-97f9-46b2-b877-c4ebe2486e7e.png)

**Comment by bling-yshs** [comment]
fov已调30

**Comment by Sapphire-356** [comment]
请问你的显示屏分辨率是多少？
因为一些事情换了一个github账号，最新的代码在Balloon-356/EyeAligningBot。

**Comment by Sapphire-356** [comment]
另外，如果出现无法检测等问题，可以通过b站私信联系我，比较方便。
按照昨天的测试，Bot在其他机子上会有一些问题。目前只有一个人提供了测试。如果你有时间，可否提供一些，在你的机子上，Bot无法工作的示例，帮助我继续改进，谢谢！

**Comment by bling-yshs** [comment]
> 另外，如果出现无法检测等问题，可以通过b站私信联系我，比较方便。 按照昨天的测试，Bot在其他机子上会有一些问题。目前只有一个人提供了测试。如果你有时间，可否提供一些，在你的机子上，Bot无法工作的示例，帮助我继续改进，谢谢！

用最新的代码可以用了诶qwq!
